version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.9.6
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  metalp-portal:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metalp_portal.rule=Host(`metalp.local`)"
      - "traefik.http.services.metalp_portal.loadbalancer.server.port=3838"
    environment:
      METALP_ENV: production
      METALP_DB_HOSTNAME: metalp-db
      METALP_DB_PORT: 3306
      METALP_DB_USERNAME: metalp
      METALP_DB_PASSWORD: metalp
      METALP_DB_NAME: metalp_db
      METALP_NOREPLY_ADDRESS: metalp-noreply@example.org
      METALP_TO_ADDRESS: metalp-noreply@example.org
    networks:
      - web
    volumes:
      - ./data:/srv/shiny-server/data
      - ./db_backups:/srv/shiny-server/db_backups
    ports:
      - "3838:3838"
    depends_on:
      - metalp-db

  metalp-db:
    image: mariadb:10.2.41
    environment:
      MYSQL_ROOT_PASSWORD: metalproot
      MYSQL_DATABASE: metalp_db
      MYSQL_USER: metalp
      MYSQL_PASSWORD: metalp
    ports:
      - 3306:3306
    volumes:
      - metalp-mariadb-data:/var/lib/mysql
    networks:
      - web

volumes:
  metalp-mariadb-data:

networks:
  web:
    driver: bridge
